# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "feat/backend-fluy"
    labels:
      - "pip dependencies"
    open-pull-requests-limit: 5
    rebase-strategy: "disabled"
    versioning-strategy: "increase-if-necessary"
