version: "1.0"

services:
  db:
    image: postgres:16.6-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"

  facture-fly:
    build:
      context: .
      dockerfile: Dockerfile
    image: facture-fly:1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - "staticfiles-data:/var/www/static"
      - "media-data:/var/www/media"
    depends_on:
      - db
    ports:
      - "8030:8030"

volumes:
  postgres-data:
  staticfiles-data:
  media-data:
